### ISSUE TITLE
Make a registration page

### ISSUE THREAD

**Issue by 287mdsahil** [287mdsahil/piradius#1]
### The registration page should ask for the following details:
- Personal Details
  - Name
  - Date of birth
  - Father's name
  - Mother's name
  - Guardian's name
- Contact Info
  - Email
  - Phone number
  - Address etc
- Academic Info
  - Appropriate fields to be added here
- Course info
  - Selected course details (options form a dropdown list)

#### The theme of the page should look exactly like the other pages.

**Comment by priyank23** [comment]
Yes Boss!
As you command, senpai!
