### ISSUE TITLE
Complete the course page

### ISSUE THREAD

**Issue by 287mdsahil** [287mdsahil/piradius#6]
It should have an option to register which will direct to the registration page

**Comment by priyank23** [comment]
@287mdsahil I think PR #9 resolves this issue. Just confirm once and close this issue after merging the PR.

**Comment by 287mdsahil** [comment]
I was thinking that each course should have a button
Tt that automatically brings up the registration page and sets the course as the current course.

Also more content needs to be added into the page
Currently the page only has the course names. We should add some details about those courses too.

**Comment by priyank23** [comment]
> sets the course as the current course

@287mdsahil Need help in doing this.

**Comment by 287mdsahil** [comment]
One solution maybe is to have a PHP variable to indicate which course is being set. If there is some mechanism to pass on that variable to the next page then it can be handled
